version: '3.8'

services:
    php:
#        image: php:8.1-fpm
        build:
            dockerfile: docker/php/Dockerfile
        volumes:
            -   './:/var/www/html'

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - './:/var/www/html'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=12345Qq=
        ports:
            -   3306:3306
        volumes:
            - './docker/volume/mysql:/var/lib/mysql'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            -   9090:80
        environment:
            -   PMA_HOST=mysql
            -   PMA_PORT=3306
